config/routes.rb
Rails.application.routes.draw do
  resources :campaigns do
    resources :student_applications
    post "import_applications" => "student_applications#import"
  end
  resources :people

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "campaigns#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/campaign.rb
class Campaign < ApplicationRecord
    validates :name, presence: true
    enum :status, { open: 0, closed: 1, archived: 2 }, prefix: true, scopes: true, default: :open, validate: true

    has_many :student_applications
end

app/models/person.rb
class Person < ApplicationRecord
    validates :name, presence: true
    validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/models/student_application.rb
class StudentApplication < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }

  belongs_to :campaign
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, only: %i[ show edit update destroy ]

  # GET /campaigns
  def index
    @campaigns = Campaign.all
  end

  # GET /campaigns/1
  def show
    @student_applications = @campaign.student_applications
  end

  # GET /campaigns/new
  def new
    @campaign = Campaign.new
  end

  # GET /campaigns/1/edit
  def edit
  end

  # POST /campaigns
  def create
    @campaign = Campaign.new(campaign_params)

    if @campaign.save
      redirect_to @campaign, notice: "Campaign was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /campaigns/1
  def update
    if @campaign.update(campaign_params)
      redirect_to @campaign, notice: "Campaign was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /campaigns/1
  def destroy
    @campaign.destroy!
    redirect_to campaigns_url, notice: "Campaign was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign
      @campaign = Campaign.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def campaign_params
      params.require(:campaign).permit(:name, :status, :accepting_reviews, :accepting_interviews)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: %i[ show edit update destroy ]

  # GET /people
  def index
    @people = Person.all
  end

  # GET /people/1
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  def create
    @person = Person.new(person_params)

    if @person.save
      redirect_to @person, notice: "Person was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /people/1
  def update
    if @person.update(person_params)
      redirect_to @person, notice: "Person was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /people/1
  def destroy
    @person.destroy!
    redirect_to people_url, notice: "Person was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:name, :email)
    end
end

app/controllers/student_applications_controller.rb
require "csv"

class StudentApplicationsController < ApplicationController
  before_action :get_campaign
  before_action :set_student_application, only: %i[ show edit update destroy ]

  # GET /student_applications
  def index
    @student_applications = @campaign.student_applications
  end

  # GET /student_applications/1
  def show
  end

  # GET /student_applications/new
  def new
    @student_application = @campaign.student_applications.build
  end

  # GET /student_applications/1/edit
  def edit
  end

  # POST /student_applications
  def create
    @student_application = StudentApplication.new(student_application_params)

    if @student_application.save
      redirect_to @student_application, notice: "Student application was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def import
    return redirect_to request.referer, notice: "No file added" if params[:file].nil?
    redirect_to request.referer, notice: "Only CSV files allowed" unless params[:file].content_type == "text/csv"

    import_csv(params[:file], @campaign.id)

    redirect_to request.referer, notice: "Import started..."
  end

  # PATCH/PUT /student_applications/1
  def update
    if @student_application.update(student_application_params)
      redirect_to [ @campaign, @student_application ], notice: "Student application was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /student_applications/1
  def destroy
    @student_application.destroy!
    redirect_to campaign_student_applications_url, notice: "Student application was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student_application
      @student_application = @campaign.student_applications.find(params[:id])
    end

    def get_campaign
      @campaign = Campaign.find(params[:campaign_id])
    end

    # Only allow a list of trusted parameters through.
    def student_application_params
      params.require(:student_application).permit(:name, :email, :question1, :question2, :question3, :question4, :question5, :campaign_id)
    end

    def import_csv(file, campaign_id)
      opened_file = File.open(file)
      options = { headers: true }
      CSV.foreach(opened_file, **options) do |row|
        # map the CSV columns to your database columns
        app_hash = {}
        app_hash[:name] = row["name"]
        app_hash[:email] = row["email"]
        app_hash[:question1] = row["question1"]
        app_hash[:question2] = row["question2"]
        app_hash[:question3] = row["question3"]
        app_hash[:question4] = row["question4"]
        app_hash[:question5] = row["question5"]
        app_hash[:campaign_id] = campaign_id

        StudentApplication.find_or_create_by!(app_hash)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/student_applications_helper.rb
module StudentApplicationsHelper
end

app/views/campaigns/_campaign.html.erb
<div id="<%= dom_id campaign %>">
  <p>
    <strong>Name:</strong>
    <%= campaign.name %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= campaign.status %>
  </p>

  <p>
    <strong>Accepting reviews:</strong>
    <%= campaign.accepting_reviews %>
  </p>

  <p>
    <strong>Accepting interviews:</strong>
    <%= campaign.accepting_interviews %>
  </p>

</div>

app/views/campaigns/_form.html.erb
<%= form_with(model: campaign) do |form| %>
  <% if campaign.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(campaign.errors.count, "error") %> prohibited this campaign from being saved:</h2>

      <ul>
        <% campaign.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.select :status, Campaign.statuses.keys %>
  </div>

  <div>
    <%= form.label :accepting_reviews, style: "display: block" %>
    <%= form.check_box :accepting_reviews %>
  </div>

  <div>
    <%= form.label :accepting_interviews, style: "display: block" %>
    <%= form.check_box :accepting_interviews %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/campaigns/edit.html.erb
<h1>Editing campaign</h1>

<%= render "form", campaign: @campaign %>

<br>

<div>
  <%= link_to "Show this campaign", @campaign %> |
  <%= link_to "Back to campaigns", campaigns_path %>
</div>

app/views/campaigns/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Campaigns</h1>

<div id="campaigns">
  <% @campaigns.each do |campaign| %>
    <%= render campaign %>
    <p>
      <%= link_to "Show this campaign", campaign %>
    </p>
  <% end %>
</div>

<%= link_to "New campaign", new_campaign_path %>

app/views/campaigns/new.html.erb
<h1>New campaign</h1>

<%= render "form", campaign: @campaign %>

<br>

<div>
  <%= link_to "Back to campaigns", campaigns_path %>
</div>

app/views/campaigns/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @campaign %>

<div>
  <%= link_to "Edit this campaign", edit_campaign_path(@campaign) %> |
  <%= link_to "Back to campaigns", campaigns_path %>

  <%= button_to "Destroy this campaign", @campaign, method: :delete %>
</div>

Applications:

<table>
  <% @student_applications.each do |student_application| %>
    <%= render 'student_applications/show_tr_short', campaign: @campaign, student_application: student_application%>
  <% end %>
</table>

<div>
  <%= render "student_applications/import", campaign: @campaign %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MmAdmin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: person) do |form| %>
  <% if person.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/people/_person.html.erb
<div id="<%= dom_id person %>">
  <p>
    <strong>Name:</strong>
    <%= person.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= person.email %>
  </p>

</div>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render "form", person: @person %>

<br>

<div>
  <%= link_to "Show this person", @person %> |
  <%= link_to "Back to people", people_path %>
</div>

app/views/people/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>People</h1>

<div id="people">
  <% @people.each do |person| %>
    <%= render person %>
    <p>
      <%= link_to "Show this person", person %>
    </p>
  <% end %>
</div>

<%= link_to "New person", new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render "form", person: @person %>

<br>

<div>
  <%= link_to "Back to people", people_path %>
</div>

app/views/people/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @person %>

<div>
  <%= link_to "Edit this person", edit_person_path(@person) %> |
  <%= link_to "Back to people", people_path %>

  <%= button_to "Destroy this person", @person, method: :delete %>
</div>

app/views/student_applications/_form.html.erb
<%= form_with(model: [@campaign, student_application]) do |form| %>
  <% if student_application.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student_application.errors.count, "error") %> prohibited this student_application from being saved:</h2>

      <ul>
        <% student_application.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :question1, style: "display: block" %>
    <%= form.text_area :question1 %>
  </div>

  <div>
    <%= form.label :question2, style: "display: block" %>
    <%= form.text_area :question2 %>
  </div>

  <div>
    <%= form.label :question3, style: "display: block" %>
    <%= form.text_area :question3 %>
  </div>

  <div>
    <%= form.label :question4, style: "display: block" %>
    <%= form.text_area :question4 %>
  </div>

  <div>
    <%= form.label :question5, style: "display: block" %>
    <%= form.text_area :question5 %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/student_applications/_import.html.erb
<%= form_tag campaign_import_applications_path(@campaign), method: :post, multipart: true do %>
  <%= file_field_tag :file, accept: ".csv" %>
  <%= submit_tag 'Import' %>
<% end %>

app/views/student_applications/_show_tr_short.html.erb
<tr>
    <td><%= student_application.name %></td>
    <td><%= student_application.email %></td>
    <td><%= link_to "Show application", [@campaign, student_application]  %></td>
</tr>

app/views/student_applications/_student_application.html.erb
<div id="<%= dom_id student_application %>">
  <p>
    <strong>Name:</strong>
    <%= student_application.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= student_application.email %>
  </p>

  <p>
    <strong>Question1:</strong>
    <%= student_application.question1 %>
  </p>

  <p>
    <strong>Question2:</strong>
    <%= student_application.question2 %>
  </p>

  <p>
    <strong>Question3:</strong>
    <%= student_application.question3 %>
  </p>

  <p>
    <strong>Question4:</strong>
    <%= student_application.question4 %>
  </p>

  <p>
    <strong>Question5:</strong>
    <%= student_application.question5 %>
  </p>

  <p>
    <strong>Campaign:</strong>
    <%= student_application.campaign_id %>
  </p>

</div>

app/views/student_applications/edit.html.erb
<h1>Editing student application</h1>

<%= render "form", student_application: @student_application %>

<br>

<div>
  <%= link_to "Show this student application", campaign_student_application_path(@campaign, @student_application) %>
  <%= link_to "Back to student applications", campaign_student_applications_path %>
</div>

app/views/student_applications/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Student applications</h1>

<div id="student_applications">
  <% @student_applications.each do |student_application| %>
    <%= render student_application %>
    <p>
      <%= link_to "Show this student application", campaign_student_application_path(@campaign, student_application) %>
    </p>
  <% end %>
</div>

<%= link_to "New student application", new_campaign_student_application_path %>

app/views/student_applications/new.html.erb
<h1>New student application</h1>

<%= render "form", student_application: @student_application %>

<br>

<div>
  <%= link_to "Back to student applications", campaign_student_applications_path %>
</div>

app/views/student_applications/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student_application %>

<div>
  <%= link_to "Edit this student application", edit_campaign_student_application_path(@campaign, @student_application) %> |
  <%= link_to "Back to student applications", campaign_student_applications_path(@campaign) %>

  <%= button_to "Destroy this student application", [@campaign, @student_application], method: :delete %>
</div>